// Production content is separate from inventory: landing pages link to the existing catalog.
export const productionCopy = {
  tr: {
    nav: 'Üretimimiz', homeTitle: 'Üretiyoruz. İşletmenizi donatıyoruz.', homeIntro: 'Paslanmaz ekipman ve plastik ambalaj üretimi; profesyonel mutfak ve kurumsal ihtiyaçlar için kapsamlı tedarik.',
    areas: 'Üretim Alanlarımız', areasIntro: 'İki üretim alanı. İşletmenizin ihtiyaçlarına özel çözümler.', discover: 'Üretimi keşfedin', catalog: 'Katalog ürünlerini inceleyin', quote: 'Üretim için teklif alın', all: 'Tüm ürünler', badge: 'Üretimimiz',
    stainless: 'Paslanmaz Ekipman Üretimi', packaging: 'Plastik Ambalaj ve Çöp Torbası Üretimi',
    stainlessIntro: 'Profesyonel mutfaklar ve çalışma alanları için paslanmaz ekipman üretiyoruz. Tezgâhtan evyeye, raf sistemlerinden proje ihtiyaçlarına kadar üretim seçeneklerimizi keşfedin.',
    packagingIntro: 'Çöp torbaları, ambalaj poşetleri ve filmler üretiyoruz. Kullanımınıza uygun ölçü, kalınlık, renk ve baskı seçeneklerini birlikte belirleyelim.',
    groups: 'Neler üretiyoruz?', options: 'İhtiyacınıza göre üretim', optionsIntro: 'Teknik özellikleri kullanım alanınıza göre birlikte netleştiriyoruz. Üretim uygunluğu, miktar ve teslimat koşulları teklif aşamasında belirlenir.',
    process: 'Talepten üretime', steps: ['İhtiyacınızı paylaşın', 'Teknik detayları netleştirelim', 'Teklifinizi onaylayın', 'Üretim ve teslimat'],
    stepTexts: ['Ürün türünü, kullanım alanını ve tahmini miktarı iletin.', 'Ölçü, malzeme ve diğer üretim seçeneklerini birlikte belirleyelim.', 'Fiyat, üretim koşulları ve teslimat planını değerlendirin.', 'Onaylanan özelliklere göre üretim ve sevkiyat sürecini yürütelim.'],
    gallery: 'Üretimden detaylar', galleryIntro: 'Üretim süreçlerimizden ve ürün hazırlığından görüntüler.', use: 'Kullanım alanları', faq: 'Sık sorulan sorular',
    questions: ['Minimum sipariş miktarı nedir?', 'Üretim ve teslimat ne kadar sürer?', 'Teknik özellikleri bilmiyorsam ne yapmalıyım?'],
    answers: ['Ürün, ölçü ve üretim özelliklerine göre belirlenir. Tahmini ihtiyacınızı paylaşarak teklif isteyebilirsiniz.', 'Sipariş miktarı, teknik detaylar ve üretim planına göre teklifinizde netleştirilir.', 'Kullanım alanınızı anlatmanız yeterli. Uygun seçenekleri birlikte belirleyebiliriz.'],
    formTitle: 'Üretim talebinizi paylaşın', formIntro: 'Bildiğiniz özellikleri yazın; diğer detayları birlikte netleştirelim. Talebiniz teklif ekibimize ulaşır.',
    family: 'Ürün grubu', size: 'Ölçü / hacim', thickness: 'Kalınlık (mikron)', color: 'Renk', print: 'Baskı / logo', quantity: 'Tahmini miktar ve birim', dimensions: 'En × boy × yükseklik (mm)', material: 'Malzeme / yüzey tercihi', note: 'Kullanım alanı ve ek bilgiler', unsure: 'Emin değilim, öneri istiyorum', noPrint: 'Baskısız', withPrint: 'Logolu / baskılı', send: 'Üretim talebini gönder', sending: 'Gönderiliyor…', success: 'Üretim talebiniz alındı.', detail: 'Talebi görüntüle', error: 'Talep gönderilemedi. Lütfen tekrar deneyin.', required: 'Adınızı, telefonunuzu ve ürün grubunu belirtin.', quantityHint: 'Örn. 10.000 adet / 500 kg', productionNote: 'Üretim talebi', specs: 'Üretim seçenekleri', related: 'Diğer üretim grupları',
    packOptions: ['Ölçü ve hacim', 'Film kalınlığı', 'Renk ve şeffaflık', 'Baskı ve paketleme'], steelOptions: ['Ölçüler', 'Çalışma alanı', 'Malzeme ve yüzey', 'Proje detayları'],
    packUses: ['Otel ve restoranlar', 'Temizlik şirketleri', 'Mağaza ve marketler', 'Çamaşırhaneler', 'Üretim ve depolama'], steelUses: ['Profesyonel mutfaklar', 'Otel ve restoranlar', 'Hazırlık ve yıkama alanları', 'Depolama ve servis'],
  },
  en: {
    nav: 'Our production', homeTitle: 'We manufacture. We equip your business.', homeIntro: 'Stainless steel equipment and plastic packaging production, with comprehensive supplies for professional kitchens and businesses.',
    areas: 'Our production areas', areasIntro: 'Two production areas. Solutions for your business.', discover: 'Explore production', catalog: 'Browse catalog products', quote: 'Request a production quote', all: 'All products', badge: 'Our production',
    stainless: 'Stainless Steel Equipment Production', packaging: 'Plastic Packaging & Garbage Bag Production', stainlessIntro: 'We manufacture stainless steel equipment for professional kitchens and workspaces. Explore worktables, sinks, shelving and solutions for your project.', packagingIntro: 'We manufacture garbage bags, packaging bags and films. Let us select the dimensions, thickness, color and printing options for your application.',
    groups: 'What we manufacture', options: 'Production for your needs', optionsIntro: 'We define specifications together for your application. Feasibility, quantities and delivery terms are confirmed in your quote.', process: 'From request to production', steps: ['Share your needs', 'Define specifications', 'Approve your quote', 'Production and delivery'], stepTexts: ['Tell us the product, application and estimated quantity.', 'Select dimensions, materials and production options together.', 'Review pricing, production terms and the delivery plan.', 'We coordinate production and dispatch to the agreed specifications.'],
    gallery: 'Inside production', galleryIntro: 'Views of our production processes and product preparation.', use: 'Applications', faq: 'Frequently asked questions', questions: ['What is the minimum order?', 'How long do production and delivery take?', 'What if I do not know the specifications?'], answers: ['It depends on the product, dimensions and specifications. Share your estimated needs to request a quote.', 'Timing is confirmed in your quote based on quantity, specifications and the production schedule.', 'Describe your application. We can help you select suitable options.'],
    formTitle: 'Tell us what you need', formIntro: 'Enter the specifications you know. We will clarify the rest with you and send your request to our quotation team.', family: 'Product group', size: 'Dimensions / volume', thickness: 'Thickness (microns)', color: 'Color', print: 'Printing / logo', quantity: 'Estimated quantity and unit', dimensions: 'Width × length × height (mm)', material: 'Material / finish', note: 'Application and additional information', unsure: 'Not sure — please advise', noPrint: 'Unprinted', withPrint: 'Printed / with logo', send: 'Send production request', sending: 'Sending…', success: 'Your production request has been received.', detail: 'View request', error: 'Unable to send. Please try again.', required: 'Please enter your name, phone and product group.', quantityHint: 'E.g. 10,000 pieces / 500 kg', productionNote: 'Production request', specs: 'Production options', related: 'Other production groups', packOptions: ['Dimensions and volume', 'Film thickness', 'Color and transparency', 'Printing and packaging'], steelOptions: ['Dimensions', 'Workspace', 'Material and finish', 'Project details'], packUses: ['Hotels and restaurants', 'Cleaning companies', 'Retail stores', 'Laundries', 'Manufacturing and storage'], steelUses: ['Professional kitchens', 'Hotels and restaurants', 'Preparation and washing areas', 'Storage and service'],
  },
  ru: {
    nav: 'Наше производство', homeTitle: 'Производим. Оснащаем ваш бизнес.', homeIntro: 'Производство оборудования из нержавеющей стали и пластиковой упаковки. Комплексное снабжение профессиональных кухонь и предприятий.', areas: 'Направления производства', areasIntro: 'Два направления производства. Решения для вашего бизнеса.', discover: 'Подробнее о производстве', catalog: 'Товары в каталоге', quote: 'Запросить расчёт', all: 'Все товары', badge: 'Наше производство', stainless: 'Производство оборудования из нержавеющей стали', packaging: 'Производство пластиковой упаковки и мусорных пакетов', stainlessIntro: 'Производим оборудование из нержавеющей стали для профессиональных кухонь и рабочих помещений: столы, мойки, стеллажи и решения для ваших проектов.', packagingIntro: 'Производим мусорные пакеты, упаковочные пакеты и плёнки. Подберём размеры, толщину, цвет и печать под ваши задачи.',
    groups: 'Что мы производим', options: 'Производство под ваши задачи', optionsIntro: 'Вместе уточним технические характеристики. Возможность изготовления, объём заказа и условия доставки определяются при расчёте предложения.', process: 'От заявки до производства', steps: ['Расскажите о задаче', 'Уточним характеристики', 'Согласуйте предложение', 'Производство и доставка'], stepTexts: ['Укажите вид продукции, применение и примерный объём.', 'Вместе определим размеры, материалы и параметры производства.', 'Рассмотрите стоимость, условия изготовления и сроки доставки.', 'Организуем производство и отгрузку по согласованным параметрам.'], gallery: 'Детали производства', galleryIntro: 'Производственные процессы и подготовка продукции.', use: 'Области применения', faq: 'Частые вопросы', questions: ['Какой минимальный заказ?', 'Сколько занимает производство и доставка?', 'Что делать, если я не знаю технических параметров?'], answers: ['Зависит от продукции, размеров и характеристик. Укажите примерную потребность для расчёта.', 'Сроки уточняются в предложении с учётом объёма, характеристик и графика производства.', 'Опишите задачу — мы поможем выбрать подходящие параметры.'],
    formTitle: 'Заявка на производство', formIntro: 'Укажите известные параметры. Остальные детали уточним вместе. Заявка поступит в отдел расчёта предложений.', family: 'Группа продукции', size: 'Размеры / объём', thickness: 'Толщина (мкм)', color: 'Цвет', print: 'Печать / логотип', quantity: 'Примерное количество и единица', dimensions: 'Ширина × длина × высота (мм)', material: 'Материал / поверхность', note: 'Применение и дополнительная информация', unsure: 'Не знаю, нужна рекомендация', noPrint: 'Без печати', withPrint: 'С печатью / логотипом', send: 'Отправить заявку', sending: 'Отправка…', success: 'Ваша заявка на производство принята.', detail: 'Посмотреть заявку', error: 'Не удалось отправить заявку. Повторите попытку.', required: 'Укажите имя, телефон и группу продукции.', quantityHint: 'Например, 10 000 шт. / 500 кг', productionNote: 'Заявка на производство', specs: 'Параметры производства', related: 'Другие группы продукции', packOptions: ['Размеры и объём', 'Толщина плёнки', 'Цвет и прозрачность', 'Печать и упаковка'], steelOptions: ['Размеры', 'Рабочее пространство', 'Материал и поверхность', 'Параметры проекта'], packUses: ['Отели и рестораны', 'Клининговые компании', 'Магазины и супермаркеты', 'Прачечные', 'Производство и склады'], steelUses: ['Профессиональные кухни', 'Отели и рестораны', 'Зоны подготовки и мойки', 'Хранение и раздача'],
  },
  kz: {
    nav: 'Біздің өндіріс', homeTitle: 'Өндіреміз. Кәсібіңізді жабдықтаймыз.', homeIntro: 'Тот баспайтын болат жабдықтар мен пластик қаптама өндірісі. Кәсіби асүйлер мен кәсіпорындарды кешенді жабдықтау.', areas: 'Өндіріс бағыттары', areasIntro: 'Екі өндіріс бағыты. Кәсібіңізге арналған шешімдер.', discover: 'Өндірісті қарау', catalog: 'Каталогтағы тауарлар', quote: 'Баға ұсынысын сұрау', all: 'Барлық тауарлар', badge: 'Біздің өндіріс', stainless: 'Тот баспайтын болат жабдықтар өндірісі', packaging: 'Пластик қаптама және қоқыс пакеттері өндірісі', stainlessIntro: 'Кәсіби асүйлер мен жұмыс орындарына арналған тот баспайтын болат жабдықтар өндіреміз: үстелдер, жуғыштар, сөрелер және жобаңызға арналған шешімдер.', packagingIntro: 'Қоқыс пакеттерін, қаптама пакеттері мен үлдірлерді өндіреміз. Қолданылуына сай өлшемін, қалыңдығын, түсін және баспасын бірге таңдаймыз.',
    groups: 'Не өндіреміз?', options: 'Қажеттілігіңізге сай өндіріс', optionsIntro: 'Техникалық сипаттамаларды бірге нақтылаймыз. Өндіру мүмкіндігі, көлемі және жеткізу шарттары ұсыныс кезінде белгіленеді.', process: 'Өтінімнен өндіріске дейін', steps: ['Қажеттілігіңізді айтыңыз', 'Сипаттамаларды нақтылаймыз', 'Ұсынысты бекітіңіз', 'Өндіріс және жеткізу'], stepTexts: ['Өнім түрін, қолданылуын және шамамен көлемін көрсетіңіз.', 'Өлшемдерді, материалды және өндіріс параметрлерін бірге анықтаймыз.', 'Бағаны, өндіріс шарттарын және жеткізу жоспарын қараңыз.', 'Бекітілген сипаттамалар бойынша өндіріс пен жөнелтуді ұйымдастырамыз.'], gallery: 'Өндіріс көріністері', galleryIntro: 'Өндіріс үдерістері мен өнімді дайындаудан көріністер.', use: 'Қолданылу салалары', faq: 'Жиі қойылатын сұрақтар', questions: ['Ең аз тапсырыс көлемі қандай?', 'Өндіріс пен жеткізу қанша уақыт алады?', 'Техникалық параметрлерді білмесем ше?'], answers: ['Өнімге, өлшемдерге және сипаттамаларға байланысты. Баға ұсынысы үшін шамамен қажеттілігіңізді көрсетіңіз.', 'Мерзім көлемге, сипаттамаларға және өндіріс кестесіне қарай ұсыныста нақтыланады.', 'Қолданылуын сипаттаңыз. Тиісті параметрлерді таңдауға көмектесеміз.'],
    formTitle: 'Өндіріске өтінім беріңіз', formIntro: 'Білетін параметрлерді енгізіңіз. Қалғанын бірге нақтылаймыз. Өтініміңіз ұсыныстар бөліміне жіберіледі.', family: 'Өнім тобы', size: 'Өлшемдер / көлем', thickness: 'Қалыңдық (мкм)', color: 'Түс', print: 'Баспа / логотип', quantity: 'Шамамен саны және бірлігі', dimensions: 'Ені × ұзындығы × биіктігі (мм)', material: 'Материал / беті', note: 'Қолданылуы және қосымша ақпарат', unsure: 'Білмеймін, кеңес қажет', noPrint: 'Баспасыз', withPrint: 'Баспа / логотиппен', send: 'Өтінімді жіберу', sending: 'Жіберілуде…', success: 'Өндіріс өтініміңіз қабылданды.', detail: 'Өтінімді қарау', error: 'Өтінім жіберілмеді. Қайталап көріңіз.', required: 'Атыңызды, телефоныңызды және өнім тобын көрсетіңіз.', quantityHint: 'Мысалы, 10 000 дана / 500 кг', productionNote: 'Өндіріс өтінімі', specs: 'Өндіріс параметрлері', related: 'Басқа өнім топтары', packOptions: ['Өлшемдер мен көлем', 'Үлдір қалыңдығы', 'Түс және мөлдірлік', 'Баспа және қаптама'], steelOptions: ['Өлшемдер', 'Жұмыс кеңістігі', 'Материал және беті', 'Жоба параметрлері'], packUses: ['Қонақүйлер мен мейрамханалар', 'Тазалық компаниялары', 'Дүкендер мен супермаркеттер', 'Кір жуатын орындар', 'Өндіріс пен қоймалар'], steelUses: ['Кәсіби асүйлер', 'Қонақүйлер мен мейрамханалар', 'Дайындау және жуу аймақтары', 'Сақтау және тарату'],
  },
};

const names = (tr, ru, kz, en) => ({ tr, ru, kz, en });
export const packagingFamilies = [
  { slug: 'garbage-bags', image: 'bags', name: names('Çöp Torbaları', 'Мусорные пакеты', 'Қоқыс пакеттері', 'Garbage Bags'), description: names('İşletmelerin atık toplama ihtiyacı için farklı hacim ve kalınlıklarda torbalar.', 'Пакеты разного объёма и толщины для сбора отходов на предприятиях.', 'Кәсіпорындарда қалдық жинауға арналған көлемі мен қалыңдығы әртүрлі пакеттер.', 'Bags in different volumes and thicknesses for business waste collection.'), specs: names(['30–240 litre', '15–60 mikron', 'Siyah ve renkli', 'Rulo veya paket'], ['30–240 литров', '15–60 мкм', 'Чёрные и цветные', 'Рулоны или упаковки'], ['30–240 литр', '15–60 мкм', 'Қара және түрлі түсті', 'Орам немесе қаптама'], ['30–240 litres', '15–60 microns', 'Black and colored', 'Rolls or packs']), catalog: '/catalog/institutional/packaging-products/cop-torbasi-ve-posetler' },
  { slug: 'polyethylene-film', image: 'film', name: names('Polietilen Ambalaj Filmleri', 'Полиэтиленовая упаковочная плёнка', 'Полиэтилен қаптама үлдірі', 'Polyethylene Packaging Film'), description: names('Ürünlerin paketlenmesi, korunması ve depolanması için polietilen film üretimi.', 'Полиэтиленовая плёнка для упаковки, защиты и хранения продукции.', 'Өнімдерді қаптау, қорғау және сақтауға арналған полиэтилен үлдір.', 'Polyethylene film for packing, protecting and storing products.') },
  { slug: 'shrink-film', image: 'shrink', name: names('Shrink Ambalaj Filmleri', 'Термоусадочная плёнка', 'Термоқысқыш үлдір', 'Shrink Packaging Film'), description: names('Tekli ve grup paketleme uygulamalarına uygun ısıyla daralan ambalaj filmleri.', 'Термоусадочная плёнка для индивидуальной и групповой упаковки.', 'Жеке және топтық қаптамаға арналған жылумен қысқаратын үлдір.', 'Heat-shrink film for individual and grouped packaging applications.') },
  { slug: 'packaging-bags', image: 'packing', name: names('Ambalaj ve Paketleme Poşetleri', 'Фасовочные и упаковочные пакеты', 'Өлшеп орау және қаптама пакеттері', 'Packing & Packaging Bags'), description: names('Kâğıt havlu, tuvalet kâğıdı ve peçete gibi ürünler için ölçüye uygun paketleme çözümleri.', 'Упаковка по размеру для бумажных полотенец, туалетной бумаги и салфеток.', 'Қағаз сүлгі, дәретхана қағазы және майлықтарға арналған өлшемге сай қаптама.', 'Sized packaging for paper towels, toilet paper and napkins.') },
  { slug: 'laundry-film', image: 'laundry', name: names('Çamaşırhane ve Kuru Temizleme Filmleri', 'Плёнка для химчисток и прачечных', 'Химиялық тазалау және кір жуу үлдірі', 'Laundry & Dry Cleaning Film'), description: names('Temizlenmiş giysi ve tekstil ürünlerini depolama ve taşıma sırasında koruyan filmler.', 'Плёнка для защиты чистой одежды и текстиля при хранении и перевозке.', 'Таза киім мен тоқыма бұйымдарын сақтау және тасымалдау кезінде қорғайтын үлдір.', 'Film to protect cleaned garments and textiles during storage and transport.') },
  { slug: 'carrier-bags', image: 'carrier', name: names('Atlet Poşetler', 'Пакеты «майка»', '«Майка» пакеттері', 'T-shirt Carrier Bags'), description: names('Mağaza, market ve paket servis için baskılı veya baskısız taşıma poşetleri.', 'Пакеты с печатью или без неё для магазинов, супермаркетов и доставки.', 'Дүкендерге, супермаркеттерге және жеткізуге арналған баспалы немесе баспасыз пакеттер.', 'Printed or unprinted carrier bags for stores, supermarkets and takeaway.') },
  { slug: 'printed-bags', image: 'printed', name: names('Logolu ve Reklam Poşetleri', 'Пакеты с логотипом', 'Логотипі бар пакеттер', 'Branded & Promotional Bags'), description: names('Markanızın görsel kimliğine uygun baskılı poşet üretimi.', 'Производство пакетов с печатью в фирменном стиле вашего бренда.', 'Брендіңіздің фирмалық стиліне сай баспалы пакеттер өндірісі.', 'Printed bags designed around your brand identity.') },
];

export const stainlessFamilies = [
  { slug: 'worktables', category: 'tezgahlar', name: names('Çalışma Tezgâhları', 'Рабочие столы', 'Жұмыс үстелдері', 'Worktables') },
  { slug: 'sink-tables', category: 'evyeli-tezgahlar', name: names('Evyeli Tezgâhlar', 'Столы с мойкой', 'Жуғышы бар үстелдер', 'Sink Tables') },
  { slug: 'shelving', category: 'raf-ve-dolap-sistemleri', name: names('Raf ve Dolap Sistemleri', 'Стеллажи и шкафы', 'Сөрелер мен шкафтар', 'Shelving & Cabinets') },
  { slug: 'dishwashing', category: 'bulasik-makinesi-tezgahlari', name: names('Bulaşıkhane Tezgâhları', 'Столы для посудомоечных зон', 'Ыдыс жуу үстелдері', 'Dishwashing Tables') },
];

// Family-specific specifications adapted from the source product pages.
export const packagingSpecifications = {
  'polyethylene-film': names(['LDPE polietilen', 'Tüp, yarım tüp veya düz film', 'Baskılı veya baskısız', 'Ölçü ve şeffaflık seçenekleri'], ['Полиэтилен ПВД', 'Рукав, полурукав или полотно', 'С печатью или без', 'Выбор размеров и прозрачности'], ['LDPE полиэтилен', 'Жең, жартылай жең немесе жайма', 'Баспалы немесе баспасыз', 'Өлшем және мөлдірлік таңдауы'], ['LDPE polyethylene', 'Tubular, centerfold or flat film', 'Printed or unprinted', 'Dimensions and transparency options']),
  'shrink-film': names(['Isıyla daralan film', 'Tekli veya grup paketleme', 'Farklı kalınlık ve ölçüler', 'Rulo halinde üretim'], ['Термоусадочная плёнка', 'Индивидуальная или групповая упаковка', 'Разная толщина и размеры', 'Производство в рулонах'], ['Жылумен қысқаратын үлдір', 'Жеке немесе топтық қаптама', 'Әртүрлі қалыңдық пен өлшем', 'Орам түрінде өндіру'], ['Heat-shrink film', 'Individual or grouped packaging', 'Thickness and size options', 'Supplied in rolls']),
  'packaging-bags': names(['Ürüne uygun ölçüler', 'Tekli ve çoklu paketleme', 'Kalınlık ve şeffaflık seçimi', 'Talebe göre logo baskısı'], ['Размеры под продукцию', 'Индивидуальная и групповая фасовка', 'Выбор толщины и прозрачности', 'Печать логотипа по запросу'], ['Өнімге сай өлшемдер', 'Жеке және топтық орау', 'Қалыңдық пен мөлдірлік таңдауы', 'Сұраныс бойынша логотип басу'], ['Product-specific dimensions', 'Individual and multipack formats', 'Thickness and transparency options', 'Logo printing on request']),
  'laundry-film': names(['Giysi ve tekstil paketleme', 'Manuel veya otomatik kullanım', 'Farklı rulo genişlikleri', 'Saklama ve taşımada koruma'], ['Упаковка одежды и текстиля', 'Ручная или автоматическая упаковка', 'Разная ширина рулонов', 'Защита при хранении и перевозке'], ['Киім мен тоқыма қаптамасы', 'Қолмен немесе автоматты орау', 'Әртүрлі орам ені', 'Сақтау және тасымалдау кезіндегі қорғаныс'], ['Garment and textile packaging', 'Manual or automatic packing', 'Different roll widths', 'Protection in storage and transit']),
  'carrier-bags': names(['HDPE polietilen', '20 mikron ve üzeri', 'Baskılı veya baskısız', 'Dört renge kadar flekso baskı'], ['Полиэтилен ПНД', 'От 20 мкм', 'С печатью или без', 'Флексопечать до четырёх цветов'], ['HDPE полиэтилен', '20 мкм-ден бастап', 'Баспалы немесе баспасыз', 'Төрт түске дейін флексобаспа'], ['HDPE polyethylene', 'From 20 microns', 'Printed or unprinted', 'Flexographic printing up to four colors']),
  'printed-bags': names(['El geçme saplı poşet', 'HDPE / LDPE seçenekleri', 'Logo ve kurumsal tasarım', 'Mağaza ve tanıtım kullanımı'], ['Пакеты с прорубной ручкой', 'Варианты ПНД / ПВД', 'Логотип и фирменный дизайн', 'Для магазинов и презентаций'], ['Ойық тұтқалы пакеттер', 'HDPE / LDPE нұсқалары', 'Логотип және фирмалық дизайн', 'Дүкендер мен таныстырылымдарға'], ['Die-cut handle bags', 'HDPE / LDPE options', 'Logo and brand artwork', 'Retail and promotional use']),
};

export function getProductionCopy(lang) { return productionCopy[lang] || productionCopy.ru; }
export function localized(value, lang) { return value?.[lang] || value?.ru || ''; }
export function getProductionGroup(product) {
  if (product?.productionGroup === 'packaging' || product?.productionGroup === 'stainless') return product.productionGroup;
  if (product?.productionGroup === 'none') return null;
  if (['paslanmaz', 'stainless', 'stainless-steel', 'stainless_steel'].includes(product?.groupKey)) return 'stainless';
  // Other packaging categories may include traded goods. Only the confirmed bag group is automatic.
  if (product?.subcategoryKey === 'cop-torbasi-ve-posetler') return 'packaging';
  return null;
}
