export {
  createUsageArea,
  deleteUsageArea,
  ensureUniqueUsageAreaSlug,
  getUsageAreaById,
  getUsageAreaBySlug,
  getUsageAreaDescription,
  getUsageAreaName,
  listUsageAreas,
  listUsageAreasEnsured,
  normalizeUsageArea,
  slugifyUsageArea,
  updateUsageArea,
  uploadUsageAreaImage,
} from "@/app/lib/usageAreas";
